# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_images']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

# # %% ../app.ipynb 2
# import pathlib
# temp = pathlib.PosixPath
# pathlib.PosixPath = pathlib.WindowsPath

# %% ../app.ipynb 4
learn = load_learner('model.pkl')

# %% ../app.ipynb 12
categories = ('Baseball', 'Basketball', 'Soccer')

def classify_images(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% ../app.ipynb 14
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()
examples = ['basketball.jpg', 'baseball.jpg', 'soccer.jpg']

intf = gr.Interface(fn=classify_images, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
